// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Integraph.Models.Common;

namespace Integraph.Models.Ifc2x3
{
    public class OptionalItemSet<T>: ItemSet<T>, IOptionalItemSet<T>
    {
        private bool _initialized;

        internal OptionalItemSet(IPersistEntity entity, int capacity, int property) : base(entity, capacity, property)
        {
        }

        public bool Initialized 
		{ 
            get { return _initialized || Count > 0; }
		}

        public void Initialize()
        {
            _initialized = true;
        }

        public void Uninitialize()
        {
            Clear();
            _initialized = false;
        }
    }
}
