// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.HVACDomain
{
	public enum IfcCondenserTypeEnum : byte
	{
		@WATERCOOLEDSHELLTUBE ,
		@WATERCOOLEDSHELLCOIL ,
		@WATERCOOLEDTUBEINTUBE ,
		@WATERCOOLEDBRAZEDPLATE ,
		@AIRCOOLED ,
		@EVAPORATIVECOOLED ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}