// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.HVACDomain
{
	public enum IfcCompressorTypeEnum : byte
	{
		@DYNAMIC ,
		@RECIPROCATING ,
		@ROTARY ,
		@SCROLL ,
		@TROCHOIDAL ,
		@SINGLESTAGE ,
		@BOOSTER ,
		@OPENTYPE ,
		@HERMETIC ,
		@SEMIHERMETIC ,
		@WELDEDSHELLHERMETIC ,
		@ROLLINGPISTON ,
		@ROTARYVANE ,
		@SINGLESCREW ,
		@TWINSCREW ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}