// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.HVACDomain
{
	public enum IfcDamperTypeEnum : byte
	{
		@CONTROLDAMPER ,
		@FIREDAMPER ,
		@SMOKEDAMPER ,
		@FIRESMOKEDAMPER ,
		@BACKDRAFTDAMPER ,
		@RELIEFDAMPER ,
		@BLASTDAMPER ,
		@GRAVITYDAMPER ,
		@GRAVITYRELIEFDAMPER ,
		@BALANCINGDAMPER ,
		@FUMEHOODEXHAUST ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}