// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.HVACDomain
{
	public enum IfcValveTypeEnum : byte
	{
		@AIRRELEASE ,
		@ANTIVACUUM ,
		@CHANGEOVER ,
		@CHECK ,
		@COMMISSIONING ,
		@DIVERTING ,
		@DRAWOFFCOCK ,
		@DOUBLECHECK ,
		@DOUBLEREGULATING ,
		@FAUCET ,
		@FLUSHING ,
		@GASCOCK ,
		@GASTAP ,
		@ISOLATING ,
		@MIXING ,
		@PRESSUREREDUCING ,
		@PRESSURERELIEF ,
		@REGULATING ,
		@SAFETYCUTOFF ,
		@STEAMTRAP ,
		@STOPCOCK ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}