// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.GeometryResource
{
	public enum IfcBSplineCurveForm : byte
	{
		@POLYLINE_FORM ,
		@CIRCULAR_ARC ,
		@ELLIPTIC_ARC ,
		@PARABOLIC_ARC ,
		@HYPERBOLIC_ARC ,
		@UNSPECIFIED 
	}
}