// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using Integraph.Models.Common.Metadata;
using Integraph.Models.Common;
using Integraph.Models.Common.Exceptions;
using Integraph.Models.Ifc2x3.Interfaces;
using Integraph.Models.Ifc2x3.PresentationDefinitionResource;
//## Custom using statements
//##

namespace Integraph.Models.Ifc2x3.Interfaces
{
	/// <summary>
    /// Readonly interface for IfcTextureCoordinate
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IIfcTextureCoordinate : IPersistEntity
	{
		IEnumerable<IIfcAnnotationSurface> @AnnotatedSurface {  get; }
	
	}
}

namespace Integraph.Models.Ifc2x3.PresentationDefinitionResource
{
	[ExpressType("IfcTextureCoordinate", 732)]
	// ReSharper disable once PartialTypeWithSinglePart
	public abstract partial class @IfcTextureCoordinate : PersistEntity, IIfcTextureCoordinate, IEquatable<@IfcTextureCoordinate>
	{
		#region IIfcTextureCoordinate explicit implementation
		 
		IEnumerable<IIfcAnnotationSurface> IIfcTextureCoordinate.AnnotatedSurface {  get { return @AnnotatedSurface; } }
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcTextureCoordinate(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}




		#region Inverse attributes
		[InverseProperty("TextureCoordinates")]
		[EntityAttribute(-1, EntityAttributeState.Mandatory, EntityAttributeType.Set, EntityAttributeType.Class, new int [] { 1 }, new int [] { 1 }, 1)]
		public IEnumerable<IfcAnnotationSurface> @AnnotatedSurface 
		{ 
			get 
			{
				return Model.Instances.Where<IfcAnnotationSurface>(e => Equals(e.TextureCoordinates), "TextureCoordinates", this);
			} 
		}
		#endregion

		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			//there are no attributes defined for this entity
            throw new System.IndexOutOfRangeException("There are no attributes defined for this entity");
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@IfcTextureCoordinate other)
	    {
	        return this == other;
	    }
        #endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}