// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.PresentationOrganizationResource
{
	public enum IfcLightEmissionSourceEnum : byte
	{
		@COMPACTFLUORESCENT ,
		@FLUORESCENT ,
		@HIGHPRESSUREMERCURY ,
		@HIGHPRESSURESODIUM ,
		@LIGHTEMITTINGDIODE ,
		@LOWPRESSURESODIUM ,
		@LOWVOLTAGEHALOGEN ,
		@MAINVOLTAGEHALOGEN ,
		@METALHALIDE ,
		@TUNGSTENFILAMENT ,
		@NOTDEFINED 
	}
}