// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc4.Interfaces
{
	public enum IfcAnalysisTheoryTypeEnum : byte
	{
		@FIRST_ORDER_THEORY ,
		@SECOND_ORDER_THEORY ,
		@THIRD_ORDER_THEORY ,
		@FULL_NONLINEAR_THEORY ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}