// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc4.Interfaces
{
	public enum IfcElementAssemblyTypeEnum : byte
	{
		@ACCESSORY_ASSEMBLY ,
		@ARCH ,
		@BEAM_GRID ,
		@BRACED_FRAME ,
		@GIRDER ,
		@REINFORCEMENT_UNIT ,
		@RIGID_FRAME ,
		@SLAB_FIELD ,
		@TRUSS ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}