// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc4.Interfaces
{
	public enum IfcLaborResourceTypeEnum : byte
	{
		@ADMINISTRATION ,
		@CARPENTRY ,
		@CLEANING ,
		@CONCRETE ,
		@DRYWALL ,
		@ELECTRIC ,
		@FINISHING ,
		@FLOORING ,
		@GENERAL ,
		@HVAC ,
		@LANDSCAPING ,
		@MASONRY ,
		@PAINTING ,
		@PAVING ,
		@PLUMBING ,
		@ROOFING ,
		@SITEGRADING ,
		@STEELWORK ,
		@SURVEYING ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}