// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc4.Interfaces
{
	public enum IfcProcedureTypeEnum : byte
	{
		@ADVICE_CAUTION ,
		@ADVICE_NOTE ,
		@ADVICE_WARNING ,
		@CALIBRATION ,
		@DIAGNOSTIC ,
		@SHUTDOWN ,
		@STARTUP ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}