// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc4.Interfaces
{
	public enum IfcPipeFittingTypeEnum : byte
	{
		@BEND ,
		@CONNECTOR ,
		@ENTRY ,
		@EXIT ,
		@JUNCTION ,
		@OBSTRUCTION ,
		@TRANSITION ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}