// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc4.Interfaces
{
	public enum IfcPropertySetTemplateTypeEnum : byte
	{
		@PSET_TYPEDRIVENONLY ,
		@PSET_TYPEDRIVENOVERRIDE ,
		@PSET_OCCURRENCEDRIVEN ,
		@PSET_PERFORMANCEDRIVEN ,
		@QTO_TYPEDRIVENONLY ,
		@QTO_TYPEDRIVENOVERRIDE ,
		@QTO_OCCURRENCEDRIVEN ,
		@NOTDEFINED 
	}
}