// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc4.Interfaces
{
	public enum IfcWindowStyleConstructionEnum : byte
	{
		@ALUMINIUM ,
		@HIGH_GRADE_STEEL ,
		@STEEL ,
		@WOOD ,
		@ALUMINIUM_WOOD ,
		@PLASTIC ,
		@OTHER_CONSTRUCTION ,
		@NOTDEFINED 
	}
}