// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.ElectricalDomain
{
	public enum IfcElectricApplianceTypeEnum : byte
	{
		@COMPUTER ,
		@DIRECTWATERHEATER ,
		@DISHWASHER ,
		@ELECTRICCOOKER ,
		@ELECTRICHEATER ,
		@FACSIMILE ,
		@FREESTANDINGFAN ,
		@FREEZER ,
		@FRIDGE_FREEZER ,
		@HANDDRYER ,
		@INDIRECTWATERHEATER ,
		@MICROWAVE ,
		@PHOTOCOPIER ,
		@PRINTER ,
		@REFRIGERATOR ,
		@RADIANTHEATER ,
		@SCANNER ,
		@TELEPHONE ,
		@TUMBLEDRYER ,
		@TV ,
		@VENDINGMACHINE ,
		@WASHINGMACHINE ,
		@WATERHEATER ,
		@WATERCOOLER ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}