// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Common;
using Integraph.Models.Ifc4.Interfaces;
//## Custom using statements
//##

namespace Integraph.Models.Ifc4.RepresentationResource
{
    // ReSharper disable once InconsistentNaming
    // ReSharper disable once PartialTypeWithSinglePart
	public partial interface IfcCoordinateReferenceSystemSelect : IIfcCoordinateReferenceSystemSelect
	{
		#region Custom code for a select
		//## Custom code for a select
		//##
		#endregion
	}
}

namespace Integraph.Models.Ifc4.Interfaces
{
	public partial interface IIfcCoordinateReferenceSystemSelect : IExpressSelectType, IPersistEntity
	{
		#region Custom code for a select interface
		//## Custom code for a select interface
		//##
		#endregion
	}
}