// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.CostResource
{
	public enum IfcEnvironmentalImpactCategoryEnum : byte
	{
		@COMBINEDVALUE ,
		@DISPOSAL ,
		@EXTRACTION ,
		@INSTALLATION ,
		@MANUFACTURE ,
		@TRANSPORTATION ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}