// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.PresentationAppearanceResource
{
	public partial class @IfcBlobTexture : IIfcBlobTexture
	{

		[CrossSchemaAttribute(typeof(IIfcBlobTexture), 6)]
		Ifc4.MeasureResource.IfcIdentifier IIfcBlobTexture.RasterFormat 
		{ 
			get
			{
				return new Ifc4.MeasureResource.IfcIdentifier(RasterFormat);
			} 
			set
			{
				RasterFormat = new MeasureResource.IfcIdentifier(value);
				
			}
		}

		[CrossSchemaAttribute(typeof(IIfcBlobTexture), 7)]
		Ifc4.MeasureResource.IfcBinary IIfcBlobTexture.RasterCode 
		{ 
			get
			{
				//## Handle return of RasterCode for which no match was found
			    return _rasterCode4;
			    //##
			} 
			set
			{
				//## Handle setting of RasterCode for which no match was found
                SetValue(v => _rasterCode4 = v, _rasterCode4, value, "RasterCode", -7);
				//##
				
			}
		}
	//## Custom code
	    private Ifc4.MeasureResource.IfcBinary _rasterCode4;
	    //##
	}
}