// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.GeometryResource
{
	public partial class @IfcCartesianTransformationOperator2D : IIfcCartesianTransformationOperator2D
	{
		List<Common.Geometry.XbimVector3D> IIfcCartesianTransformationOperator2D.U 
		{
			get 
			{
				return U;
			}
		}

	//## Custom code
	//##
	}
}