// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.GeometryResource
{
	public partial class @IfcDirection : IIfcDirection
	{

		[CrossSchemaAttribute(typeof(IIfcDirection), 1)]
		IItemSet<Integraph.Models.Ifc4.MeasureResource.IfcReal> IIfcDirection.DirectionRatios 
		{ 
			get
			{
				//## Handle return of DirectionRatios for which no match was found
                return new Common.Collections.ProxyValueSet<double, Ifc4.MeasureResource.IfcReal>(DirectionRatios,
                    s => new Ifc4.MeasureResource.IfcReal(s),
                    t => t);
			    //##
			} 
		}
		Ifc4.GeometryResource.IfcDimensionCount IIfcDirection.Dim 
		{
			get 
			{
				return new Ifc4.GeometryResource.IfcDimensionCount(Dim);
			}
		}

	//## Custom code
	//##
	}
}