// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.PresentationAppearanceResource
{
	public partial class @IfcFillAreaStyleTiles : IIfcFillAreaStyleTiles
	{

		[CrossSchemaAttribute(typeof(IIfcFillAreaStyleTiles), 1)]
		IEnumerable<IIfcVector> IIfcFillAreaStyleTiles.TilingPattern 
		{ 
			get
			{
				//## Handle return of TilingPattern for which no match was found
			    yield return TilingPattern.RepeatFactor;
			    //##
			} 
		}

		[CrossSchemaAttribute(typeof(IIfcFillAreaStyleTiles), 2)]
		IEnumerable<IIfcStyledItem> IIfcFillAreaStyleTiles.Tiles 
		{ 
			get
			{
				//## Handle return of Tiles for which no match was found
			    return Tiles.OfType<IfcFillAreaStyleTileSymbolWithStyle>().Select(tile => tile.Symbol.Item).OfType<IIfcStyledItem>();
			    //##
			} 
		}

		[CrossSchemaAttribute(typeof(IIfcFillAreaStyleTiles), 3)]
		Ifc4.MeasureResource.IfcPositiveRatioMeasure IIfcFillAreaStyleTiles.TilingScale 
		{ 
			get
			{
				return new Ifc4.MeasureResource.IfcPositiveRatioMeasure(TilingScale);
			} 
			set
			{
				TilingScale = new MeasureResource.IfcPositiveRatioMeasure(value);
				
			}
		}
	//## Custom code
	//##
	}
}