// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.PresentationAppearanceResource
{
	public partial class @IfcFillAreaStyle : IIfcFillAreaStyle
	{

		[CrossSchemaAttribute(typeof(IIfcFillAreaStyle), 2)]
		IItemSet<IIfcFillStyleSelect> IIfcFillAreaStyle.FillStyles 
		{ 
			get
			{
			
				return new Common.Collections.ProxyItemSet<IfcFillStyleSelect, IIfcFillStyleSelect>(FillStyles);
			} 
		}

		private  Ifc4.MeasureResource.IfcBoolean? _modelorDraughting;


		[CrossSchemaAttribute(typeof(IIfcFillAreaStyle), 3)]
		Ifc4.MeasureResource.IfcBoolean? IIfcFillAreaStyle.ModelorDraughting 
		{ 
			get
			{
				return _modelorDraughting;
			} 
			set
			{
				SetValue(v => _modelorDraughting = v, _modelorDraughting, value, "ModelorDraughting", -3);
				
			}
		}
	//## Custom code
	//##
	}
}