// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.GeometricModelResource
{
	public partial class @IfcFaceBasedSurfaceModel : IIfcFaceBasedSurfaceModel
	{

		[CrossSchemaAttribute(typeof(IIfcFaceBasedSurfaceModel), 1)]
		IItemSet<IIfcConnectedFaceSet> IIfcFaceBasedSurfaceModel.FbsmFaces 
		{ 
			get
			{
			
				return new Common.Collections.ProxyItemSet<TopologyResource.IfcConnectedFaceSet, IIfcConnectedFaceSet>(FbsmFaces);
			} 
		}
		Ifc4.GeometryResource.IfcDimensionCount IIfcFaceBasedSurfaceModel.Dim 
		{
			get 
			{
				return new Ifc4.GeometryResource.IfcDimensionCount(Dim);
			}
		}

	//## Custom code
	//##
	}
}