// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.Kernel
{
	public partial class @IfcProduct : IIfcProduct
	{

		[CrossSchemaAttribute(typeof(IIfcProduct), 6)]
		IIfcObjectPlacement IIfcProduct.ObjectPlacement 
		{ 
			get
			{
				return ObjectPlacement;
			} 
			set
			{
				ObjectPlacement = value as GeometricConstraintResource.IfcObjectPlacement;
				
			}
		}

		[CrossSchemaAttribute(typeof(IIfcProduct), 7)]
		IIfcProductRepresentation IIfcProduct.Representation 
		{ 
			get
			{
				return Representation;
			} 
			set
			{
				Representation = value as RepresentationResource.IfcProductRepresentation;
				
			}
		}
		IEnumerable<IIfcRelAssignsToProduct> IIfcProduct.ReferencedBy 
		{ 
			get
			{
				return Model.Instances.Where<IIfcRelAssignsToProduct>(e => (e.RelatingProduct as IfcProduct) == this, "RelatingProduct", this);
			} 
		}
	//## Custom code
	//##
	}
}