// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.Kernel
{
	public partial class @IfcProcess : IIfcProcess
	{

		private  Ifc4.MeasureResource.IfcIdentifier? _identification;


		[CrossSchemaAttribute(typeof(IIfcProcess), 6)]
		Ifc4.MeasureResource.IfcIdentifier? IIfcProcess.Identification 
		{ 
			get
			{
				return _identification;
			} 
			set
			{
				SetValue(v => _identification = v, _identification, value, "Identification", -6);
				
			}
		}

		private  Ifc4.MeasureResource.IfcText? _longDescription;


		[CrossSchemaAttribute(typeof(IIfcProcess), 7)]
		Ifc4.MeasureResource.IfcText? IIfcProcess.LongDescription 
		{ 
			get
			{
				return _longDescription;
			} 
			set
			{
				SetValue(v => _longDescription = v, _longDescription, value, "LongDescription", -7);
				
			}
		}
		IEnumerable<IIfcRelSequence> IIfcProcess.IsPredecessorTo 
		{ 
			get
			{
				return Model.Instances.Where<IIfcRelSequence>(e => (e.RelatingProcess as IfcProcess) == this, "RelatingProcess", this);
			} 
		}
		IEnumerable<IIfcRelSequence> IIfcProcess.IsSuccessorFrom 
		{ 
			get
			{
				return Model.Instances.Where<IIfcRelSequence>(e => (e.RelatedProcess as IfcProcess) == this, "RelatedProcess", this);
			} 
		}
		IEnumerable<IIfcRelAssignsToProcess> IIfcProcess.OperatesOn 
		{ 
			get
			{
				return Model.Instances.Where<IIfcRelAssignsToProcess>(e => (e.RelatingProcess as IfcProcess) == this, "RelatingProcess", this);
			} 
		}
	//## Custom code
	//##
	}
}