// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.PresentationResource
{
	public partial class @IfcPlanarExtent : IIfcPlanarExtent
	{

		[CrossSchemaAttribute(typeof(IIfcPlanarExtent), 1)]
		Ifc4.MeasureResource.IfcLengthMeasure IIfcPlanarExtent.SizeInX 
		{ 
			get
			{
				return new Ifc4.MeasureResource.IfcLengthMeasure(SizeInX);
			} 
			set
			{
				SizeInX = new MeasureResource.IfcLengthMeasure(value);
				
			}
		}

		[CrossSchemaAttribute(typeof(IIfcPlanarExtent), 2)]
		Ifc4.MeasureResource.IfcLengthMeasure IIfcPlanarExtent.SizeInY 
		{ 
			get
			{
				return new Ifc4.MeasureResource.IfcLengthMeasure(SizeInY);
			} 
			set
			{
				SizeInY = new MeasureResource.IfcLengthMeasure(value);
				
			}
		}
	//## Custom code
	//##
	}
}