// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.QuantityResource
{
	public partial class @IfcQuantityVolume : IIfcQuantityVolume
	{

		[CrossSchemaAttribute(typeof(IIfcQuantityVolume), 4)]
		Ifc4.MeasureResource.IfcVolumeMeasure IIfcQuantityVolume.VolumeValue 
		{ 
			get
			{
				return new Ifc4.MeasureResource.IfcVolumeMeasure(VolumeValue);
			} 
			set
			{
				VolumeValue = new MeasureResource.IfcVolumeMeasure(value);
				
			}
		}

		private  Ifc4.MeasureResource.IfcLabel? _formula;


		[CrossSchemaAttribute(typeof(IIfcQuantityVolume), 5)]
		Ifc4.MeasureResource.IfcLabel? IIfcQuantityVolume.Formula 
		{ 
			get
			{
				return _formula;
			} 
			set
			{
				SetValue(v => _formula = v, _formula, value, "Formula", -5);
				
			}
		}
	//## Custom code
	//##
	}
}