// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.Kernel
{
	public partial class @IfcRelAssociates : IIfcRelAssociates
	{

		[CrossSchemaAttribute(typeof(IIfcRelAssociates), 5)]
		IItemSet<IIfcDefinitionSelect> IIfcRelAssociates.RelatedObjects 
		{ 
			get
			{
				//## Handle return of RelatedObjects for which no match was found
                return new Common.Collections.VolatileProxyItemSet<IfcRoot, IIfcDefinitionSelect>(RelatedObjects);
				//##
			} 
		}
	//## Custom code
	//##
	}
}