// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.Kernel
{
	public partial class @IfcRelAssignsToResource : IIfcRelAssignsToResource
	{

		private  IIfcResourceSelect _relatingResource4;


		[CrossSchemaAttribute(typeof(IIfcRelAssignsToResource), 7)]
		IIfcResourceSelect IIfcRelAssignsToResource.RelatingResource 
		{ 
			get
			{
				return  _relatingResource4 ?? RelatingResource;
			} 
			set
			{
				if (value == null)
				{
					RelatingResource = null;
					if (_relatingResource4 != null)
						SetValue(v => _relatingResource4 = v, _relatingResource4, null, "RelatingResource", -7);
					return;
				}
				
				var val = value as IfcResource;
				if (val != null)
				{
					RelatingResource = val;
					if (_relatingResource4 != null)
						SetValue(v => _relatingResource4 = v, _relatingResource4, null, "RelatingResource", -7);
					return;
				} 

				if(RelatingResource != null)
					RelatingResource = null;
				SetValue(v => _relatingResource4 = v, _relatingResource4, value, "RelatingResource", -7);
				
			}
		}
	//## Custom code
	//##
	}
}