// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.StructuralAnalysisDomain
{
	public partial class @IfcRelConnectsWithEccentricity : IIfcRelConnectsWithEccentricity
	{

		[CrossSchemaAttribute(typeof(IIfcRelConnectsWithEccentricity), 11)]
		IIfcConnectionGeometry IIfcRelConnectsWithEccentricity.ConnectionConstraint 
		{ 
			get
			{
				return ConnectionConstraint;
			} 
			set
			{
				ConnectionConstraint = value as GeometricConstraintResource.IfcConnectionGeometry;
				
			}
		}
	//## Custom code
	//##
	}
}