// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.ProductExtension
{
	public partial class @IfcRelCoversSpaces : IIfcRelCoversSpaces
	{

		[CrossSchemaAttribute(typeof(IIfcRelCoversSpaces), 5)]
		IIfcSpace IIfcRelCoversSpaces.RelatingSpace 
		{ 
			get
			{
				return RelatedSpace;
			} 
			set
			{
				RelatedSpace = value as IfcSpace;
				
			}
		}

		[CrossSchemaAttribute(typeof(IIfcRelCoversSpaces), 6)]
		IItemSet<IIfcCovering> IIfcRelCoversSpaces.RelatedCoverings 
		{ 
			get
			{
			
				return new Common.Collections.ProxyItemSet<IfcCovering, IIfcCovering>(RelatedCoverings);
			} 
		}
	//## Custom code
	//##
	}
}