// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.ProductExtension
{
	public partial class @IfcRelFillsElement : IIfcRelFillsElement
	{

		[CrossSchemaAttribute(typeof(IIfcRelFillsElement), 5)]
		IIfcOpeningElement IIfcRelFillsElement.RelatingOpeningElement 
		{ 
			get
			{
				return RelatingOpeningElement;
			} 
			set
			{
				RelatingOpeningElement = value as IfcOpeningElement;
				
			}
		}

		[CrossSchemaAttribute(typeof(IIfcRelFillsElement), 6)]
		IIfcElement IIfcRelFillsElement.RelatedBuildingElement 
		{ 
			get
			{
				return RelatedBuildingElement;
			} 
			set
			{
				RelatedBuildingElement = value as IfcElement;
				
			}
		}
	//## Custom code
	//##
	}
}