// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.Kernel
{
	public partial class @IfcRelAssignsToActor : IIfcRelAssignsToActor
	{

		[CrossSchemaAttribute(typeof(IIfcRelAssignsToActor), 7)]
		IIfcActor IIfcRelAssignsToActor.RelatingActor 
		{ 
			get
			{
				return RelatingActor;
			} 
			set
			{
				RelatingActor = value as IfcActor;
				
			}
		}

		[CrossSchemaAttribute(typeof(IIfcRelAssignsToActor), 8)]
		IIfcActorRole IIfcRelAssignsToActor.ActingRole 
		{ 
			get
			{
				return ActingRole;
			} 
			set
			{
				ActingRole = value as ActorResource.IfcActorRole;
				
			}
		}
	//## Custom code
	//##
	}
}