// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.PresentationAppearanceResource
{
	public partial class @IfcSurfaceStyleWithTextures : IIfcSurfaceStyleWithTextures
	{

		[CrossSchemaAttribute(typeof(IIfcSurfaceStyleWithTextures), 1)]
		IItemSet<IIfcSurfaceTexture> IIfcSurfaceStyleWithTextures.Textures 
		{ 
			get
			{
			
				return new Common.Collections.ProxyItemSet<IfcSurfaceTexture, IIfcSurfaceTexture>(Textures);
			} 
		}
	//## Custom code
	//##
	}
}