// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Integraph.Models.Common;

// ReSharper disable once CheckNamespace
namespace Integraph.Models.Ifc2x3.GeometryResource
{
	public partial class @IfcSweptSurface : IIfcSweptSurface
	{

		[CrossSchemaAttribute(typeof(IIfcSweptSurface), 1)]
		IIfcProfileDef IIfcSweptSurface.SweptCurve 
		{ 
			get
			{
				return SweptCurve;
			} 
			set
			{
				SweptCurve = value as ProfileResource.IfcProfileDef;
				
			}
		}

		[CrossSchemaAttribute(typeof(IIfcSweptSurface), 2)]
		IIfcAxis2Placement3D IIfcSweptSurface.Position 
		{ 
			get
			{
				return Position;
			} 
			set
			{
				Position = value as IfcAxis2Placement3D;
				
			}
		}
	//## Custom code
	//##
	}
}