// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.ProductExtension
{
	public enum IfcCoveringTypeEnum : byte
	{
		@CEILING ,
		@FLOORING ,
		@CLADDING ,
		@ROOFING ,
		@INSULATION ,
		@MEMBRANE ,
		@SLEEVING ,
		@WRAPPING ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}