// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.SharedBldgServiceElements
{
	public enum IfcDistributionChamberElementTypeEnum : byte
	{
		@FORMEDDUCT ,
		@INSPECTIONCHAMBER ,
		@INSPECTIONPIT ,
		@MANHOLE ,
		@METERCHAMBER ,
		@SUMP ,
		@TRENCH ,
		@VALVECHAMBER ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}