// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.SharedBldgServiceElements
{
	public enum IfcThermalLoadSourceEnum : byte
	{
		@PEOPLE ,
		@LIGHTING ,
		@EQUIPMENT ,
		@VENTILATIONINDOORAIR ,
		@VENTILATIONOUTSIDEAIR ,
		@RECIRCULATEDAIR ,
		@EXHAUSTAIR ,
		@AIREXCHANGERATE ,
		@DRYBULBTEMPERATURE ,
		@RELATIVEHUMIDITY ,
		@INFILTRATION ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}