// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Integraph.Models.Ifc2x3.StructuralAnalysisDomain
{
	public enum IfcStructuralCurveTypeEnum : byte
	{
		@RIGID_JOINED_MEMBER ,
		@PIN_JOINED_MEMBER ,
		@CABLE ,
		@TENSION_MEMBER ,
		@COMPRESSION_MEMBER ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}