// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Integraph.Models.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Integraph.Models.Ifc2x3.MeasureResource;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using Integraph.Models.Common.Metadata;
using Integraph.Models.Common;
using Integraph.Models.Common.Exceptions;
using Integraph.Models.Ifc2x3.Interfaces;
using Integraph.Models.Ifc2x3.ExternalReferenceResource;
//## Custom using statements
//##

namespace Integraph.Models.Ifc2x3.Interfaces
{
	/// <summary>
    /// Readonly interface for IfcClassificationNotationFacet
    /// </summary>
	// ReSharper disable once PartialTypeWithSinglePart
	public partial interface @IIfcClassificationNotationFacet : IPersistEntity
	{
		IfcLabel @NotationValue { get;  set; }
	
	}
}

namespace Integraph.Models.Ifc2x3.ExternalReferenceResource
{
	[ExpressType("IfcClassificationNotationFacet", 251)]
	// ReSharper disable once PartialTypeWithSinglePart
	public  partial class @IfcClassificationNotationFacet : PersistEntity, IInstantiableEntity, IIfcClassificationNotationFacet, IEquatable<@IfcClassificationNotationFacet>
	{
		#region IIfcClassificationNotationFacet explicit implementation
		IfcLabel IIfcClassificationNotationFacet.NotationValue { 
 
			get { return @NotationValue; } 
			set { NotationValue = value;}
		}	
		 
		#endregion

		//internal constructor makes sure that objects are not created outside of the model/ assembly controlled area
		internal IfcClassificationNotationFacet(IModel model, int label, bool activated) : base(model, label, activated)  
		{
		}

		#region Explicit attribute fields
		private IfcLabel _notationValue;
		#endregion
	
		#region Explicit attribute properties
		[EntityAttribute(1, EntityAttributeState.Mandatory, EntityAttributeType.None, EntityAttributeType.None, null, null, 1)]
		public IfcLabel @NotationValue 
		{ 
			get 
			{
				if(_activated) return _notationValue;
				Activate();
				return _notationValue;
			} 
			set
			{
				SetValue( v =>  _notationValue = v, _notationValue, value,  "NotationValue", 1);
			} 
		}	
		#endregion




		#region IPersist implementation
		public override void Parse(int propIndex, IPropertyValue value, int[] nestedIndex)
		{
			switch (propIndex)
			{
				case 0: 
					_notationValue = value.StringVal;
					return;
				default:
					throw new XbimParserException(string.Format("Attribute index {0} is out of range for {1}", propIndex + 1, GetType().Name.ToUpper()));
			}
		}
		#endregion

		#region Equality comparers and operators
        public bool Equals(@IfcClassificationNotationFacet other)
	    {
	        return this == other;
	    }
        #endregion

		#region Custom code (will survive code regeneration)
		//## Custom code
		//##
		#endregion
	}
}